[build]
  command = "bundle config set path 'vendor/bundle' && bundle install && bundle exec compass compile --config='./compass-config.rb'"
  edge_functions = "netlify/edge-functions"
  publish = "./public"

[build.environment]
  RUBY_VERSION = "3.1.5"

[dev]
  command = "sh dev.sh"
  framework = "#static"
  publish = "./public"